apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:UlH4LMhtIqAYQIXg+VOzG/c0iRpqYJwvYgOLO0VA5mGJSaOukT3UTd9vP855hJNSmlgN7dBkNtVw5MVwKDTlToy0tY/lkSai6t7ywRpco+qEYx2rp0WfPN5lSJGWigOJ4klZWVZtPF0YZQ4V6aizcqULoBsLM68aIo9eImUGydOToGOd8PX4nqSAfKM32sfcVvQCILRVzq9stdUpGdc7UcRiUbUIr2XcISB5+AR6GQ8BswmOfNA+0ku5XLOZRMzqXOy9gUS/+vEZNVV28r80BemRjDIgCX1FaNJIjOXG+ZxzPd8eUnItT6bAi6lhD8g2UJWNp92QNnRpdndwVxh/758kmMQ7in9MfNMrpINQuDaTpJ2KDXamlA4jq5Ki1UEOV2Qkj9+bGKa4A+C7tMEq1KUbvej+OAEsSkN7KrCk78ftYFXxP1I9udPeQxGY0OsG/ERdZrJQO7pixsTSfHSgTD8t+E9zD7DlFhxtrpBW+aupJ7m7aht77aBnJnahtXtpipUXMHmdnpdy1heKBKFLhIZ79r3wR7Z1W8lAAGMM5cJGqV//GlVRatlWpBVLMAylzOuWVGZnb7xCxq2SFCkygOBBy2L5Mt/TzELjt0jYkiHxCd+0k5VO+HPIYrXMrXeqw8lc0hW1NUWFxPvaQkPsfD3zlgYeMdawIzyNfdRG4La61rJCzL5J1qPonw3nVi3Cr33PYwO3m8/y5Rrfws5YfA537EZDw+pjjmpSx8AgEm2t4C4RZFaWYElOhXaB9W4c,iv:sR3aQzV+bu3F9sfgSo2w1ZZfL6sg6S4Ato4+9eYMbK4=,tag:YgiamqvvUIh7XHxPFHvlqw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
    namespace: synology-csi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gq4w8g5q8y8ddj3mynp6fa03x5rxpus36lugjlehgef44gdqm9jqj6e404
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbGF2VmxNc0ZCOC9kaGlo
            Yno3aU9VUlJFdFpzVHU2czF4VUtGajN5dVZzCkhSQjlTSlY1VVhDcjdmSkFrdjVu
            R3FyUGFBckFRRlBsMTU2NnFwNjRhMmsKLS0tIFF2SXZlZWl6UVZHVTBMcUY2aDhk
            TUtmTU1lWm5CNzJENVR1bG1ieU5FS0EKShq12EJDL18u5IN7hKE7+hbvk/Y7kRLS
            nxsMDXxvzKAIysecooD8jG/KcuuTidwTbbEb+KVEVOAPTWgpEIIjjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T08:48:35Z"
    mac: ENC[AES256_GCM,data:i3kWw0Yx9EihU5f70X0HYBP6JyuEaX5s2iUfv0Q3L2/ieCTp84BkHRDJ347CWTNGDCMsNwW3xvfzbUoc8KZU02EZL5twcIM3JYbGmXh7ZhQtWGggemsewRiW5kyK2cUWmkyQRqmwtMN7ZtUlylktCLO/j0rt+GzkMMRuKSjhhzM=,iv:xXWUz7TUlmSin59sS4/PW2NjI/6ez9KvBNn667HUrUI=,tag:2m0yxhl/UKTdORwXIQxZMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
