apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.uclab8.net:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
        namespace: external-secrets
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
