apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-synology-secret
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-synology-credentials
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_SYNOLOGY_USERNAME
      remoteRef:
        key: homepage-synology
        property: username
    - secretKey: HOMEPAGE_SYNOLOGY_PASSWORD
      remoteRef:
        key: homepage-synology
        property: password
