apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        fsGroup: 1000 # www-data group ID
        runAsUser: 1000 # www-data user ID
        runAsGroup: 1000 # www-data group ID

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/db
                    operator: NotIn
                    values:
                      - "true"

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.8.0

          envFrom:
            - configMapRef:
                name: mealie-configmap
            - secretRef:
                name: mealie-container-env
          ports:
            - containerPort: 9000
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
          claimName: mealie-data-pvc
