apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:F4IZZPffHEDNJMj3Y3lANA3tnIu3wygj62o9EtZIVVPoqXQ98OmAenpcG4fEgHvUvMO+RPmuKPsvZlcA5KNMy73+fkfJTUAfeXrACnlkjAFMOHAFCYx7phxAJpAH/kpmCFu3CCS1NsI49gA8zAxfet2rWV1POZlX9h1A67IFNPQ03NnkImOaNIPHeZ8QBPAoSqpztO8tkJDZTiakFrxIqGb6HDb+JPPWoB506ud4DkeAIUMOMVHN8nlsW1iunRYghPIKgpwhdzNk4pjq1sXhKJR/1Br60hVz,iv:6NRLWL3aqISWdcE4BE4aO11dpamlyuR01eUuS8RwfoA=,tag:bvOu8wx4NQYLYsI/9dSI0g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gq4w8g5q8y8ddj3mynp6fa03x5rxpus36lugjlehgef44gdqm9jqj6e404
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWxsRTg1VHpFOU93QVNP
            ME9KS3czS2VEbFpMSGxQb2JzVHdNT2k4MFVNCmtwUExZdnFzNTB2MlJtV3I2SUJ6
            aWVJQTNxR1dnWUxzc1NOV3UrbUxEbEEKLS0tIG4ydHplZVZmZnEzUkFqQ2VxZ2w4
            Z2E2NTJLejczU0NhTThnR3ZFaC9yYzgKIa6FV+aBi0ZJ6GlrtNGVwOl2C6BUCjL4
            qTYRw5pbO0OlFV9/DVNfkKXan0m2V8reeJbLDNWEryEuCO9AWBrXvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T16:52:55Z"
    mac: ENC[AES256_GCM,data:BUhJe/5FDokkKdMcc9MP/a6zpf/fn5yCSEdbSVTJDEIUl36woasM3NgLT/4x50VY5yaQES2vSZT8Ihrw4d4BYx5pEpauB6QtiRIK31OAfE6J0uEHGHFNJgQgIx2ByPCiCapGhjiBwTTEdE0cmkRN0E3DS7e7xtMyOcmPgKwBfX4=,iv:trfsVeeOAnuboICaif25lZD3FkPxcj2PqyfYnk5ea/o=,tag:z8k48AIw0JSiiG0Q62FyXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
