apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:Bp29hwayr2hZyRv4YI9Flv22QkbY4IsQYiWHQ/mr7rIBzV4jobbRAw==,iv:2bQzE46pOjIADRW1b5WJcvpO87bUvcWNnpv2UxIe5AA=,tag:UvxQS7XLYOuz3eJpm5J6jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gq4w8g5q8y8ddj3mynp6fa03x5rxpus36lugjlehgef44gdqm9jqj6e404
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNXE4SXU0Z1NMU2hoRTNv
            NnUwcDVNZzBTM0l4RmJ0UDUwS3NydGRzNVR3CjZrNGhQQ0VIenZCSld4TnVrd3hT
            dmZwaWE3WThiRmg4eEtWRFVKWkNpYWsKLS0tIFJXUmlVQ2tXWTFxTG9nNDEyV050
            em90L3owSm1ZblNHTWJmcVM2NXhEd0EKPAN+rJiT7tO+VxD5uj81lb/nbGLPTmnn
            YhPeuHaVnPPvhTLC+/fLwXl5j3Vk5xFLuMK5JnhKppBB89wS17+oJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T14:34:23Z"
    mac: ENC[AES256_GCM,data:xEEDEes1EDtBjpyzUPd03IQuNX1Qhe7qC9irNWvvaKLgw3DEcKD5sLiHC+DKZnY3/Gc6w59SC5MsNuBplPfQNSlBcWhN4A76iXIX1F0oTLiLalpCM685RPHiXKmLEQbcdcTUnWAO6fYsiYToU5HNXlb9OYMkaJTYQjz7EBOMRp8=,iv:KDQbgeXr/EbTq/o+XqSbr/dWV/riLw32S+PG6DJs9LI=,tag:bNU/p5cg+RGcg4yI9pra1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
