apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-api-token
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-dns-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-dns-api-token
      remoteRef:
        key: secret-cf-token
        property: cloudflare-token
