apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        # allowPrivilegeEscalation: false
        # runAsNonRoot: true
        #   capabilities:
        #     drop: ["ALL"]
        #   seccompProfile:
        #     type: "RuntimeDefault"
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      nodeSelector:
        kubernetes.io/hostname: k8s-worker-prod-01

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.20.0
          ports:
            - containerPort: 3005
          volumeMounts:
            - name: audiobookshelf-audiobooks
              mountPath: /audiobooks
            - name: audiobookshelf-config
              mountPath: /config
            - name: audiobookshelf-metadata
              mountPath: /metadata

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
