apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commafeed
resources:
  - namespace.yaml
  - commafeed-db-creds.yaml
  - minio-s3-secret.yaml
  - barmanobjectstore.yaml
  - database.yaml
  # - scheduled-backup.yaml
  # - commafeed-db.yaml
