apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed-configmap
data:
  LD_SERVER_PORT: "3003"
  LD_DB_ENGINE: postgres
  LD_DB_DATABASE: commafeed
  LD_DB_PORT: "5432"
  LD_DB_HOST: commafeed-db-v0.linkding.svc.cluster.local
