apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag

  template:
    metadata:
      labels:
        app: wallabag

    spec:
      # envsubst in the entrypoint sh needs to write to /etc/php
      # securityContext:
      #   runAsUser: 101
      #   runAsGroup: 101
      #   fsGroup: 101

      containers:
        - name: wallabag
          image: ghcr.io/wallabag/docker:2.6.13

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: wallabag-configmap
            - secretRef:
                name: wallabag-container-env
          ports:
            - containerPort: 80
              protocol: TCP
      #     volumeMounts:
      #       - name: wallabag-data
      #         mountPath: /var/www/wallabag/data
      #       - name: wallabag-images
      #         mountPath: /var/www/wallabag/web/assets/images
      #
      # volumes:
      #   - name: wallabag-data
      #     persistentVolumeClaim:
      #       claimName: wallabag-data-pvc
      #   - name: wallabag-images
      #     persistentVolumeClaim:
      #       claimName: wallabag-images-pvc
      restartPolicy: Always
