apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-container-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wallabag-container-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: wallabag-container-env
        property: wallabag-db-password
    - secretKey: SYMFONY__ENV__DATABASE_PASSWORD
      remoteRef:
        key: wallabag-container-env
        property: wallabag-symphony-password
