apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - namespace.yaml
  - minio-s3-secret.yaml
  - barmanobjectstore.yaml
  - wallabag-db-creds.yaml
  # - database.yaml
  - scheduled-backup.yaml
  - wallabag-db.yaml
