apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
    - Social:
        - Linkdin:
            - abbr: LD
              href: https://linkdin.com/
    - News:
        - Protothema:
            - abbr: PT
              href: https://protothema.gr/

  services.yaml: |
    - My First Group:
        - Atlas:
            href: https://atlas.uclab8.net:5001
            description: atlas.uclab8.net
            icon: synology
            widget:
              type: diskstation
              url: https://atlas.uclab8.net:5001
              username: '{{ .Env.HOMEPAGE_SYNOLOGY_USERNAME }}'
              password: '{{ .Env.HOMEPAGE_SYNOLOGY_PASSWORD }}'
              volume: volume_1

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
