apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-container-env
  namespace: mealie
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mealie-container-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: mealie-container-env
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: mealie-container-env
        property: POSTGRES_PASSWORD
