cloneStaticSiteFromGit:
  enabled: true
  repository: "git@github.com:affragak/blog.git"
  branch: main
  gitClone:
    command:
      - /bin/bash
      - -ec
      - |
        [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
        git clone {{ .Values.cloneStaticSiteFromGit.repository }} --branch {{ .Values.cloneStaticSiteFromGit.branch }} /tmp/app
        [[ "$?" -eq 0 ]] && shopt -s dotglob && rm -rf /app/* && mv /tmp/app/* /app/

ingress:
  enabled: true
  hostname: dev.uclab8.net
  ingressClassName: traefik
  tls: true
  annotations: {
    cert-manager.io/cluster-issuer: letsencrypt-staging
  }
serverBlock: |-
  server {
    listen 8080;
    root /app/public;
    index index.html;
  }
service:
  type: ClusterIP
