apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      org: empire
  # externalIPs: true
  loadBalancerIPs: true
