apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: w1-lb-pool
  namespace: kube-system
spec:
  blocks:
    - start: "10.10.10.20"
      stop: "10.10.10.29"
  serviceSelector:
    matchLabels:
      org: worker1
