apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: w1-l2-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      org: worker1
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - k8s-worker-prod-01
  externalIPs: true
  loadBalancerIPs: true
