apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: linkding
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-linkding
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare-tunnel-linkding
        property: file
