apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-ng-config
data:
  syslog-ng.conf: |
    @version: current
    @include "scl.conf"
    source s_local {
    internal();
    };

    source s_network {
    default-network-drivers(
    );
    };
    destination d_local {
        file("/var/log/messages");
    };
    log {
        source(s_local);
        source(s_network);
        destination(d_local);
    };
