apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-ng-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 2Gi
