grafana:
  adminPassword: grafana123
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts:
      - monitoring.uclab8.net

  persistence:
    enabled: true
    type: sts
    storageClassName: synology-iscsi-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
