grafana:
  adminPassword: grafana123
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts:
      - grafana.uclab8.net

  persistence:
    enabled: true
    type: sts
    storageClassName: synology-iscsi-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  additionalScrapeConfigs:
    - job_name: "kubernetes-endpoints"
      scrape_interval: 30s
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels:
            [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels:
            [
              __address__,
              __meta_kubernetes_service_annotation_prometheus_io_port,
            ]
          action: replace
          target_label: __address__
          regex: (.+)(?::\d+);(\d+)
          replacement: $1:$2
#

