apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: commafeed-container-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: commafeed-container-env
    creationPolicy: Owner
  data:
    - secretKey: quarkus.datasource.username
      remoteRef:
        key: commafeed-container-env
        property: CF_DB_USER
    - secretKey: quarkus.datasource.password
      remoteRef:
        key: commafeed-container-env
        property: CF_DB_PASSWORD
